# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  Unit-Tests:
    docker:
      - image: circleci/openjdk:13.0-buster
    steps:
      - run:
          name: Run Unit Tests
          command: |
            mvn clean test

  Integration-Tests:
    docker:
      - image: circleci/openjdk:13.0-buster
    steps:
      - run:
          name: Run Integration Tests
          command: |
            mvn clean -P test-it test

  Build:
    docker:
      - image: circleci/openjdk:13.0-buster
    steps:
      - run:
          name: Build Image
          command: |
            mvn clean install

workflows:
  version: 2
  Build_Workflow:
    jobs:
      - Unit-Tests
      - Integration-Tests
      - Build:
          type: approval
          requires:
            - Unit-Tests
            - Integration-Tests